services:
  jellyfin-auto-collections:
    #build: .
    image: ghcr.io/julescls/jellyfin-auto-collections:latest
    container_name: jellyfin-auto-collections
    environment:
      - CRONTAB=0 0 * * *
      - TZ=Europe/Paris
      - JELLYFIN_SERVER_URL=https://www.jellyfin.example.com
      - JELLYFIN_API_KEY=1a1111aa1a1a1aaaa11a11aa111aaa11
      - JELLYFIN_USER_ID=2b2222bb2b2b2bbbb22b22bb222bbb22
    volumes:
      - ${CONF_DIR}/jellyfin-auto-collections/config:/app/config
    restart: unless-stopped
